services:
  webcord:
    image: lscr.io/linuxserver/webcord:latest
    container_name: webcord
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - webcord:/config
    shm_size: "1gb"
    restart: unless-stopped

  nso-rpc:
    image: ghcr.io/hotarublaze/nso-rpc-docker:latest
    build: .
    container_name: nso-rpc
    network_mode: service:webcord
    stdin_open: true
    tty: true
    volumes:
      - nso-rpc:/root/Documents/NSO-RPC
    restart: unless-stopped

volumes:
  nso-rpc:
  webcord: